### Introduction:

    For our project we decided to compare economic data with election data to see how the economy might impact elections. We wanted to determine whether poor economic performance according to several important economic indicators such as the unemployment rate, CPI (consumer price index), and GDP (gross domestic product) are strongly correlated with a change in office in presidential electoral years. We also wanted to see whether one party is disproportionately impacted by economic performance. Much can be learned from an analysis of economic and electoral data. With a data set containing economic indicators, voting proportion by party, voting counts by party, president elected, and the party of the president elect, much analysis can be performed. This was the goal for our project. 
    We ultimately ended up with a dataset that had the following structure. Columns included
State, Total Votes, Republican Votes, Republican Percentage (proportion of total votes for democratic presidential candidate), Republican Electoral (the number of electoral votes gained by Republicans), Democratic Votes, Democratic Percentage (proportion of total votes for democratic presidential candidate), Democratic Electoral  (the number of electoral votes gained by Democrats), President Elect, Winning Party, Unemployment Rate, GDP, CPI, Month, Year, and finally Election Cycle (year the president was elected). Each observation of the dataset is unique by state, month, and year. The economic data is by each month of the President’s term during their presidency. We felt that the structure of the this data would best prepare us for analysis of economic and electoral performance.
    Keeping the data unique by state allowed for us to evaluate how voting proportions varied by state in each presidential election year. The dataset we created allows for a wide range of analysis to be performed and many different insights to be learned. This data and analysis might be of interest to political parties in seeing how the performance of their party impacts them or whether they need to make the economy a bigger priority in their campaigning. It could also potentially influence undecided voters if their analysis yielded certain results. It is important to mention that the purpose of this project is not to try and promote either party and our analysis remained factual and politically neutral.

### Data collection:

    Obtaining our raw data was an intensive process. We gathered data from various sources, including the Bureau of Labor Statistics (https://www.bls.gov), and the American Presidency Project (https://www.presidency.ucsb.edu/statistics/elections). Our data collection methods were in accordance with the terms and conditions. The BLS statistics were acquired after requesting an API from the website. They encourage analysis using their data so obtaining csv files was a simple and quick process. After the data was obtained the separate csv files required some cleaning using the pandas package in python. Following this the economic data was compiled into one csv file. The code for this process can be found on the economic_data.ipynb file on our GitHub repository. The election data was scraped from the American Presidency Project website. The website contains a page for each election year in the United States. Beautiful Soup was used to scrape these tables and pandas was ultimately used to combine each scraped table. Due to formatting and HTML inconsistencies, these tables needed to be scraped one at a time, cleaned, and then ultimately compiled into one main dataset on president electoral data. This code can be found in the president_data,ipynb file on our GitHub repository. Our data was then combined into one cleaned csv in the merged_data.ipynb file. Ultimately our dataset includes election data from 1948 onwards as well as the GDP, CPI and unemployment rates for every month from 1948 until now as well.

### Data wrangling:

    Most of the wrangling needed to be done on our data occurred in our script folder in the files mentioned in the data collection section above. The methods of data wrangling included renaming columns using the rename function in pandas, or by simply creating new variables in our data frames. Regex expressions were also used to strip values in the data and prepare them for analysis. Once values were stripped and columns were renamed, we were ready to merge the csv files. This process was surprisingly straightforward. In order to keep the data unique by state, month, and year, we created a new variable titled Election Cycle. This variable recorded the year each president was elected and re-elected. Creating this variable required some simple math. The Year variable was subtracted from the starting point, 1948, and then floor division was used by 4 to obtain the same value across all 4 years of a presidential term. Then the value was multiplied by 4 and the starting year, 1948 was added back. This resulted in an accurate variable that gave the election year for every presidential term served since 1948. The data was then merged on Election Cycle using a left join. This gave every state, month, and year it’s unique value while also correctly combining economic and electoral data. The desired columns were then selected for the final dataset and the data frame was written to a csv file. 

#### Package Functions:

     Wrangling and analysis functions were written in our package folder in order to perform analysis on our developed web application. Our wrangling functions include wrangle_data(), merge_sort_data, add_presidents_to_data, and get_presidents_html. The wrangle_data() function takes in raw data from the API and uses regex expressions to provide analysis ready values in a dataset. The merge_sort_data() can be used to combine data from the different indicators into one dataset. The add_presidents_to_data() function adds a string with the president to economic data using the month and year, as well as an HTML parser. Lastly, the get_presidents_html() function retrieves the wikipedia HTML presidential content when given proper inputs. 
    In our analysis document we have three functions that help users to perform analysis and gain insights directly on our application. The first function is titled economic_trends_for_president(). This function takes in a data frame, a president, an indicator, and term. Based on these inputs, the function returns a data frame with the selected president, which economic indicators were selected, and which term is desired. This function is used in our application to plot the economic data of a given president over the course of the terms they served. The next function, simple_eda() prepares cleaned data for basic exploratory data analysis of economic and electoral factors by party. The function is used on our application to display a correlation matrix, as well as linear regression plots of voting proportions and economic performance. The last function, president_party_and_economic_analysis() prepares information to be displayed for a specific president. The function determines how long the president was in office, the economic changes across there entire presidency, economic changes in their final year as president, where the next president belonged to the same party or a different party, and lastly, a table displaying shifts of voter proportions in the next election. This function helps viewers to evaluate presidential performance. More about our function be found under the demo page.

### Insights and Findings:

    In our analysis we saw several interesting trends and patterns. Firstly, we can conclude that electoral performance does not impact either party disproportionally. Looking specifically at our correlation matrix, we see that the correlation between economic indicators and democratic and republican voting proportions is rather minimal. With correlation coefficients of -0.01 among Republican voting percentage and 0.08 among Democrat voting percentage with GDP, -0.02 and 0.07 with CPI, and 0.01 and 0.00, we can see that neither party has a strong statistical relationship between presidential electoral performance and economic indicators. It is interesting to note however, that there is a 0.1 percent difference in correlation coefficient values between the two parties. Additionally, the regression plots showed not difference in voting percentage as values for each of our economic indicators increase. 
    Look at the economic trends by each president during their terms served, it appears that there is no clear pattern by party. On insight gained is that regardless of president or party, GDP and CPI frequent show very steady increases throughout each president’s terms served. This shows us that both gross domestic product and inflation do not appear to be very dependent on which party controls the administrative branch. It would be interesting to try and determine other factors or variables that are driving the content increase in gross domestic product and inflation, as well as how the two variables impact each other. Furthermore, across all presidencies, unemployment rate appears to frequently be the most volatile economic indicator. 
    Finally, looking at the presidency analysis sections, we can evaluate each individual President’s performance throughout there presidency as well as the election results of the next election. On insight gained by this is that if a president served two terms, it is very likely that the next president will be from the opposing party.  Also poor economic indicators in the final year of the sitting president’s term appear to be more impactful than the economic performance over the course of their entire presidency. Looking at the change in proportions by state, we also concluded that poor economic performance of a president does appear to reduce voting proportions across states. Interestingly enough, swing states do not appear to generally have significant swings in voting proportion. This shows that the margins of a president being elected are almost always razor thin.